In [1]:
from kw_x12_parser import full_parse_x837p, casual_parse_x837p

In [2]:
from pathlib import Path

In [3]:
# casual parsing example (takes only the most important columns)
# we will be using this parsed DF to show the workflow of write_to_edi_x837p method

# File in same dir as notebook; or use ../x837p_edi_examples/edi_sample_25_claims.txt
df1 = casual_parse_x837p("../x837p_edi_examples/edi_sample_25_claims.txt")

edi_path = Path("../x837p_edi_examples/edi_sample_25_claims.txt")
original_text = edi_path.read_text(encoding="utf-8")

df1["original_837_edi_test"] = original_text

print(f"Shape: {df1.shape[0]} rows x {df1.shape[1]} cols")
df1.head()

Shape: 25 rows x 12 cols

,provider_name,provider_npi,provider_address,provider_city_state_zip,claim_id,total_charge,patient_name,payer_name,diagnosis_codes,service_line_count,source_file,original_837_edi_test
0,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772246,1419.22,SUSAN WILLIAMS,DEMO PRIMARY PAYER,Z933|L89151|K5720|L97222,4,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
1,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772245,1385.15,MARY WILLIAMS,DEMO PRIMARY PAYER,Z932|N39498|S31114D|R262,4,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
2,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772244,856.34,JOHN RODRIGUEZ,DEMO PRIMARY PAYER,G4733|N39498|L89151|L89151,4,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
3,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772243,133.90,JOHN MILLER,DEMO PRIMARY PAYER,I872|Z433|R339,1,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
4,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772242,2703.81,ROBERT TAYLOR,DEMO PRIMARY PAYER,Z932|K5720|J9601,4,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...

In [4]:
# casual parsing example (takes only the most important columns)

df2 = casual_parse_x837p("../x837p_edi_examples/edi_sample_50_claims.txt")
print(f"Shape: {df2.shape[0]} rows x {df2.shape[1]} cols")
df2.head()

Shape: 50 rows x 11 cols

,provider_name,provider_npi,provider_address,provider_city_state_zip,claim_id,total_charge,patient_name,payer_name,diagnosis_codes,service_line_count,source_file
0,DEMO DME PROVIDER LLC,1578990689,467 EXAMPLE WAY,"GA, 30044",52224943,1551.24,ELIZABETH DAVIS,DEMO PRIMARY PAYER,G4733|Z433|N39498,4,edi_sample_50_claims.txt
1,DEMO DME PROVIDER LLC,1578990689,467 EXAMPLE WAY,"GA, 30044",52224942,2454.60,KAREN LOPEZ,DEMO PRIMARY PAYER,R0902|J9601|S31114D|S31114D,4,edi_sample_50_claims.txt
2,DEMO DME PROVIDER LLC,1578990689,467 EXAMPLE WAY,"GA, 30044",52224941,1461.07,JAMES SMITH,DEMO PRIMARY PAYER,I872|S31114D,3,edi_sample_50_claims.txt
3,DEMO DME PROVIDER LLC,1578990689,467 EXAMPLE WAY,"GA, 30044",52224940,1384.53,LINDA RODRIGUEZ,DEMO PRIMARY PAYER,R32|R339|R339,3,edi_sample_50_claims.txt
4,DEMO DME PROVIDER LLC,1578990689,467 EXAMPLE WAY,"GA, 30044",52224939,1478.55,MICHAEL DAVIS,DEMO PRIMARY PAYER,M5432|N39498,2,edi_sample_50_claims.txt

In [5]:
# full parsing example (parse all columns in detail)

df3 = full_parse_x837p("../x837p_edi_examples/edi_sample_75_claims.txt")

edi_path = Path("../x837p_edi_examples/edi_sample_75_claims.txt")
original_text = edi_path.read_text(encoding="utf-8")

df3["original_837_edi_test"] = original_text

print(f"Shape: {df3.shape[0]} rows x {df3.shape[1]} cols")
df3.head()

Shape: 75 rows x 451 cols

,claim_id,provider_name,provider_npi,ST_Transaction_Set_Identifier_Code,ST_Transaction_Set_Control_Number,BHT_Date,BHT_Time,BHT_Reference_Identification,CLM_Claim_Submitters_Identifier,CLM_Monetary_Amount,...,SVD_5_Amount,SVD_5_Composite,SVD_5_PayerIdentifier,SVD_6_Amount,SVD_6_Composite,SVD_6_PayerIdentifier,TRANSACTION_ID,file_name,source_file,original_837_edi_test
0,52058893-1000,DEMO DME PROVIDER LLC,1503517893,837,0001,20260218,1441,100000202,52058893-1000,1789.98,...,64.53,HC:E0601,62308,NaN,NaN,NaN,100000202,edi_sample_75_claims.txt,edi_sample_75_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
1,52058892-1001,DEMO DME PROVIDER LLC,1503517893,837,0001,20260218,1441,100000202,52058892-1001,701.29,...,NaN,NaN,NaN,NaN,NaN,NaN,100000202,edi_sample_75_claims.txt,edi_sample_75_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
2,52058891-1002,DEMO DME PROVIDER LLC,1503517893,837,0001,20260218,1441,100000202,52058891-1002,2390.92,...,509.96,HC:K0004,95327,186.25,HC:E0630,95327,100000202,edi_sample_75_claims.txt,edi_sample_75_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
3,52058890-1003,DEMO DME PROVIDER LLC,1503517893,837,0001,20260218,1441,100000202,52058890-1003,1229.38,...,NaN,NaN,NaN,NaN,NaN,NaN,100000202,edi_sample_75_claims.txt,edi_sample_75_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
4,52058889-1004,DEMO DME PROVIDER LLC,1503517893,837,0001,20260218,1441,100000202,52058889-1004,2406.90,...,582.42,HC:E1390,95327,NaN,NaN,NaN,100000202,edi_sample_75_claims.txt,edi_sample_75_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...

In [6]:
# test for stitching back claims into EDI format on claims deletion from original EDI file.
# randomly remove 10 rows from the dataframe; this is to simulate claims being held, which in this case is 10, and the rest are set to be released.

import random

rows_to_drop = random.sample(list(df1.index), 10)
df_reduced = df1.drop(rows_to_drop)

print(f"Original: {df1.shape[0]} rows x {df1.shape[1]} cols")
print(f"Reduced:  {df_reduced.shape[0]} rows x {df_reduced.shape[1]} cols")
df_reduced.head()

Original: 25 rows x 12 cols
Reduced:  15 rows x 12 cols

,provider_name,provider_npi,provider_address,provider_city_state_zip,claim_id,total_charge,patient_name,payer_name,diagnosis_codes,service_line_count,source_file,original_837_edi_test
0,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772246,1419.22,SUSAN WILLIAMS,DEMO PRIMARY PAYER,Z933|L89151|K5720|L97222,4,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
3,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772243,133.90,JOHN MILLER,DEMO PRIMARY PAYER,I872|Z433|R339,1,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
5,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772241,1056.48,KAREN RODRIGUEZ,DEMO PRIMARY PAYER,K219|R339|N39498|R339,4,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
6,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772240,788.98,LINDA WILLIAMS,DEMO PRIMARY PAYER,Z932|L97222|L89151,1,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
7,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772239,523.53,MARY MILLER,DEMO PRIMARY PAYER,Z933|N39498,2,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...

In [7]:
from kw_x12_parser import write_to_edi_x837p

# original EDI text and filename from the DataFrame
original_text = df_reduced["original_837_edi_test"].iloc[0]
original_filename = df_reduced["source_file"].iloc[0]

write_to_edi_x837p(
    df_reduced,
    original_filename,
    original_edi=original_text,
)

# The result is a new EDI file with the same name as the original file, but with the claims removed from the block above.

In [8]:
# test to see if the resulting EDI file is parsable 

df1 = casual_parse_x837p("edi_sample_25_claims.txt")

edi_path = Path("edi_sample_25_claims.txt")
original_text = edi_path.read_text(encoding="utf-8")

df1["original_837_edi_test"] = original_text

print(f"Shape: {df1.shape[0]} rows x {df1.shape[1]} cols")
df1.head()

# from the result below, we are able to parse the output EDI file from above successfully.

Shape: 15 rows x 12 cols

,provider_name,provider_npi,provider_address,provider_city_state_zip,claim_id,total_charge,patient_name,payer_name,diagnosis_codes,service_line_count,source_file,original_837_edi_test
0,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772246,1419.22,SUSAN WILLIAMS,DEMO PRIMARY PAYER,Z933|L89151|K5720|L97222,4,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
1,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772243,133.90,JOHN MILLER,DEMO PRIMARY PAYER,I872|Z433|R339,1,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
2,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772241,1056.48,KAREN RODRIGUEZ,DEMO PRIMARY PAYER,K219|R339|N39498|R339,4,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
3,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772240,788.98,LINDA WILLIAMS,DEMO PRIMARY PAYER,Z932|L97222|L89151,1,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...
4,DEMO DME PROVIDER LLC,1796233790,381 EXAMPLE WAY,"GA, 31401",52772239,523.53,MARY MILLER,DEMO PRIMARY PAYER,Z933|N39498,2,edi_sample_25_claims.txt,ISA*00* *00* *ZZ*99999DEMO ...